#!/usr/bin/env pwsh
# Materialize Phase-2 five-node fleet crew files from one local manifest.

param(
    [string]$Manifest = "phase2-fleet.local.json",
    [string]$Node = "all",
    [string]$OutDir = ".ensemble/phase2-fleet",
    [switch]$InitSample,
    [switch]$Force,
    [switch]$Materialize,
    [switch]$CheckNodes,
    [switch]$PlanOnly,
    [switch]$SelfTest
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Fail([string]$Message) {
    Write-Host "FAIL: $Message" -ForegroundColor Red
    exit 1
}

function Get-Prop($Object, [string]$Name, $Default = $null) {
    if ($null -eq $Object) {
        return $Default
    }
    $prop = $Object.PSObject.Properties[$Name]
    if ($null -eq $prop) {
        return $Default
    }
    return $prop.Value
}

function Require-Prop($Object, [string]$Name, [string]$Path) {
    $value = Get-Prop $Object $Name $null
    if ($null -eq $value -or ([string]$value).Trim().Length -eq 0) {
        Fail "manifest is missing required field: $Path.$Name"
    }
    return [string]$value
}

function Toml-String([string]$Value) {
    $escaped = $Value.Replace('\', '\\').Replace('"', '\"')
    $escaped = $escaped.Replace("`r", '\r').Replace("`n", '\n').Replace("`t", '\t')
    return '"' + $escaped + '"'
}

function Quote-Arg([string]$Value) {
    if ([string]::IsNullOrEmpty($Value)) {
        return "''"
    }
    return "'" + $Value.Replace("'", "''") + "'"
}

function Resolve-ManifestPath([string]$Path) {
    if ([System.IO.Path]::IsPathRooted($Path)) {
        return [System.IO.Path]::GetFullPath($Path)
    }
    return [System.IO.Path]::GetFullPath((Join-Path (Get-Location) $Path))
}

function Resolve-FromBase([string]$Base, [string]$Path) {
    if ([System.IO.Path]::IsPathRooted($Path)) {
        return [System.IO.Path]::GetFullPath($Path)
    }
    return [System.IO.Path]::GetFullPath((Join-Path $Base $Path))
}

function Normalize-NodeUrl([string]$NodeName) {
    $trimmed = $NodeName.Trim().TrimEnd('/')
    if ($trimmed.Length -eq 0) {
        Fail "node name must not be blank"
    }
    if ($trimmed.StartsWith("http://") -or $trimmed.StartsWith("https://")) {
        return $trimmed
    }
    if ($trimmed -match '^[^:/\[\]]+:\d+$') {
        return "http://$trimmed"
    }
    if ($trimmed.StartsWith("[") -and $trimmed.Contains("]")) {
        if ($trimmed -match '^\[[^\]]+\]:\d+$') {
            return "http://$trimmed"
        }
        return "http://$trimmed`:7878"
    }
    if ($trimmed.Contains(":") -and -not $trimmed.StartsWith("[")) {
        return "http://[$trimmed]:7878"
    }
    return "http://$trimmed`:7878"
}

function Get-UrlHosts([string]$Text) {
    $hosts = New-Object System.Collections.Generic.List[string]
    foreach ($match in [regex]::Matches($Text, 'https?://(\[[^\]]+\]|[^/:\s]+)(?::\d+)?')) {
        $hosts.Add($match.Groups[1].Value.Trim('[', ']'))
    }
    return $hosts
}

function Get-ExpectedHost([string]$NodeName) {
    $trimmed = $NodeName.Trim().TrimEnd('/')
    $match = [regex]::Match($trimmed, '^(?:https?://)?(\[[^\]]+\]|[^/:\s]+)(?::\d+)?(?:/.*)?$')
    if ($match.Success) {
        return $match.Groups[1].Value.Trim('[', ']')
    }
    return $trimmed.Trim('[', ']')
}

function Test-HostPresent([string]$ExpectedNode, [string[]]$Hosts) {
    $expected = Get-ExpectedHost $ExpectedNode
    foreach ($hostName in $Hosts) {
        if ($hostName.Equals($expected, [System.StringComparison]::OrdinalIgnoreCase)) {
            return $true
        }
        if ($hostName.StartsWith("$expected.", [System.StringComparison]::OrdinalIgnoreCase)) {
            return $true
        }
    }
    return $false
}

function New-MainCrewText($Main) {
    $routes = Get-Prop $Main "routes" $null
    if ($null -eq $routes) {
        Fail "manifest is missing required field: main.routes"
    }
    $codexNode = Normalize-NodeUrl (Require-Prop $routes "codex" "main.routes")
    $claudeNode = Normalize-NodeUrl (Require-Prop $routes "claude" "main.routes")
    $agyNode = Normalize-NodeUrl (Require-Prop $routes "agy" "main.routes")
    $testCommand = [string](Get-Prop $Main "test" "cargo test --quiet")

    $lines = @(
        "# Generated by scripts/phase2-fleet.ps1. Do not edit by hand.",
        "# Edit the manifest, then rerun the script.",
        "# opencode is intentionally excluded from headless governed roles until its",
        "# non-interactive approval/hang behavior is stable.",
        'pipeline = ["implement", "review", "audit"]',
        "",
        "[gate]",
        "min_approvals = 2",
        "max_rounds = 2",
        'on_flake = "exclude"',
        "stall_limit = 0",
        "max_task_secs = 0",
        "",
        "[test]",
        "command = $(Toml-String $testCommand)",
        "",
        "[roles.implement]",
        'agent = "codex"',
        "",
        "[roles.review]",
        'agent = "claude"',
        "blind = true",
        "",
        "[roles.audit]",
        'agent = "agy"',
        "blind = true",
        "",
        "[agents.codex]",
        "node = $(Toml-String $codexNode)",
        "timeout = 60",
        'backup = "agy"',
        "",
        "[agents.claude]",
        "node = $(Toml-String $claudeNode)",
        "timeout = 60",
        'backup = "agy"',
        "",
        "[agents.agy]",
        "node = $(Toml-String $agyNode)",
        "timeout = 180"
    )
    return ($lines -join [Environment]::NewLine) + [Environment]::NewLine
}

function New-SatelliteCrewText($Satellite) {
    $nodeUrl = Normalize-NodeUrl (Require-Prop $Satellite "node" "satellites[]")
    $testCommand = [string](Get-Prop $Satellite "test" "cargo test --quiet")

    $lines = @(
        "# Generated by scripts/phase2-fleet.ps1. Do not edit by hand.",
        "# Edit the manifest, then rerun the script.",
        "# Satellite governed role set is codex + claude only.",
        'pipeline = ["implement", "review"]',
        "",
        "[gate]",
        "min_approvals = 1",
        "max_rounds = 3",
        'on_flake = "exclude"',
        "",
        "[test]",
        "command = $(Toml-String $testCommand)",
        "",
        "[roles.implement]",
        'agent = "codex"',
        "",
        "[roles.review]",
        'agent = "claude"',
        "blind = true",
        "",
        "[agents.codex]",
        "node = $(Toml-String $nodeUrl)",
        "timeout = 120",
        "",
        "[agents.claude]",
        "node = $(Toml-String $nodeUrl)",
        "timeout = 150"
    )
    return ($lines -join [Environment]::NewLine) + [Environment]::NewLine
}

function New-RunCommand([string]$Task, [string]$Crew, [string]$Repo, [string]$Team, [string]$Watch, [bool]$Merge) {
    $parts = @(
        "ensemble",
        "run",
        (Quote-Arg $Task),
        "--crew",
        (Quote-Arg $Crew),
        "--repo",
        (Quote-Arg $Repo),
        "--team",
        (Quote-Arg $Team),
        "--watch",
        (Quote-Arg $Watch)
    )
    if ($Merge) {
        $parts += "--merge"
    }
    return ($parts -join " ")
}

function Select-Node([string]$Candidate) {
    return $Node -eq "all" -or $Node -eq $Candidate
}

function New-FleetPlan($Fleet, [string]$ManifestDir) {
    $nodes = @(Get-Prop $Fleet "nodes" @())
    if ($nodes.Count -eq 0) {
        Fail "manifest.nodes must contain m1..m5 (or your mapped host names)"
    }
    $conductor = [string](Get-Prop $Fleet "conductor" $nodes[0])
    $main = Get-Prop $Fleet "main" $null
    if ($null -eq $main) {
        Fail "manifest is missing required field: main"
    }
    $mainRepo = Resolve-FromBase $ManifestDir (Require-Prop $main "repo" "main")
    $mainTeam = [string](Get-Prop $main "team" "main")
    $mainWatch = [string](Get-Prop $main "watch" $mainTeam)
    $mainTask = [string](Get-Prop $main "task" "phase2 main smoke run")
    $mainMerge = [bool](Get-Prop $main "merge" $true)
    $mainOutDir = Resolve-FromBase $mainRepo $OutDir
    $mainCrew = Resolve-FromBase $mainOutDir "crew-main.generated.toml"
    $projects = @()
    $commands = @()

    foreach ($fleetNode in $nodes) {
        if (Select-Node ([string]$fleetNode)) {
            $commands += [pscustomobject]@{
                Node = [string]$fleetNode
                Kind = "service"
                Text = "ensemble up"
            }
        }
    }

    $mainSelected = Select-Node $conductor
    $projects += [pscustomobject]@{
        Kind     = "main"
        Name     = "main"
        Node     = $conductor
        Repo     = $mainRepo
        Crew     = $mainCrew
        Text     = New-MainCrewText $main
        Selected = $mainSelected
    }
    if ($mainSelected) {
        $commands += [pscustomobject]@{
            Node = $conductor
            Kind = "run"
            Text = New-RunCommand $mainTask $mainCrew $mainRepo $mainTeam $mainWatch $mainMerge
        }
        $commands += [pscustomobject]@{
            Node = $conductor
            Kind = "watch"
            Text = "ensemble watch $(Quote-Arg $mainWatch) --repo $(Quote-Arg $mainRepo) --team $(Quote-Arg $mainTeam) --follow"
        }
    }

    $satellites = @(Get-Prop $Fleet "satellites" @())
    foreach ($sat in $satellites) {
        $satName = Require-Prop $sat "name" "satellites[]"
        $satNode = Require-Prop $sat "node" "satellites[$satName]"
        $satRepo = Resolve-FromBase $ManifestDir (Require-Prop $sat "repo" "satellites[$satName]")
        $satTeam = [string](Get-Prop $sat "team" $satName)
        $satWatch = [string](Get-Prop $sat "watch" $satTeam)
        $satTask = [string](Get-Prop $sat "task" "phase2 satellite smoke run")
        $satOutDir = Resolve-FromBase $satRepo $OutDir
        $satCrew = Resolve-FromBase $satOutDir "crew-$satName.generated.toml"
        $satSelected = Select-Node $satNode
        $projects += [pscustomobject]@{
            Kind     = "satellite"
            Name     = $satName
            Node     = $satNode
            Repo     = $satRepo
            Crew     = $satCrew
            Text     = New-SatelliteCrewText $sat
            Selected = $satSelected
        }
        if ($satSelected) {
            $commands += [pscustomobject]@{
                Node = $satNode
                Kind = "run"
                Text = New-RunCommand $satTask $satCrew $satRepo $satTeam $satWatch $false
            }
            $commands += [pscustomobject]@{
                Node = $satNode
                Kind = "watch"
                Text = "ensemble watch $(Quote-Arg $satWatch) --repo $(Quote-Arg $satRepo) --team $(Quote-Arg $satTeam) --follow"
            }
        }
    }

    return [pscustomobject]@{
        Nodes     = @($nodes | ForEach-Object { [string]$_ })
        Conductor = $conductor
        Projects  = $projects
        Commands  = $commands
    }
}

function Read-FleetManifest([string]$Path) {
    if (-not (Test-Path -LiteralPath $Path)) {
        Fail "manifest not found: $Path (use -InitSample first)"
    }
    return Get-Content -Raw -LiteralPath $Path | ConvertFrom-Json
}

function Write-Plan($Plan) {
    Write-Host "Fleet nodes: $($Plan.Nodes -join ', ')"
    Write-Host "Conductor : $($Plan.Conductor)"
    Write-Host ""
    Write-Host "Generated crew files:"
    foreach ($project in $Plan.Projects) {
        $mark = if ($project.Selected) { "*" } else { " " }
        Write-Host (" {0} [{1}] {2} on {3}" -f $mark, $project.Kind, $project.Crew, $project.Node)
    }
    Write-Host ""
    Write-Host "Commands:"
    foreach ($cmd in $Plan.Commands) {
        Write-Host ("[{0}] {1}" -f $cmd.Node, $cmd.Text)
    }
}

function Materialize-Plan($Plan) {
    foreach ($project in $Plan.Projects) {
        if (-not $project.Selected) {
            continue
        }
        if (-not (Test-Path -LiteralPath $project.Repo -PathType Container)) {
            Fail "$($project.Kind) repo for '$($project.Name)' is not accessible: $($project.Repo)"
        }
        $dir = Split-Path -Parent $project.Crew
        New-Item -ItemType Directory -Force -Path $dir | Out-Null
        Set-Content -LiteralPath $project.Crew -Value $project.Text -Encoding utf8NoBOM
        Write-Host "wrote $($project.Crew)"
    }
}

function Check-FleetNodes($Plan) {
    if (-not (Get-Command ensemble -ErrorAction SilentlyContinue)) {
        Fail "ensemble is not on PATH; install first"
    }
    $meshOut = & ensemble mesh 2>&1
    $meshCode = $LASTEXITCODE
    $meshText = ($meshOut | Out-String)
    Write-Host $meshText.TrimEnd()
    if ($meshCode -ne 0) {
        Fail "ensemble mesh exited $meshCode"
    }
    $nodesOut = & ensemble nodes 2>&1
    $nodesCode = $LASTEXITCODE
    $nodesText = ($nodesOut | Out-String)
    Write-Host $nodesText.TrimEnd()
    if ($nodesCode -ne 0) {
        Fail "ensemble nodes exited $nodesCode"
    }
    $hosts = @(Get-UrlHosts $meshText)
    $expectedRemoteNodes = @($Plan.Nodes | Where-Object {
            -not ([string]$_).Equals($Plan.Conductor, [System.StringComparison]::OrdinalIgnoreCase)
        })
    $missing = New-Object System.Collections.Generic.List[string]
    foreach ($fleetNode in $expectedRemoteNodes) {
        if (-not (Test-HostPresent $fleetNode $hosts)) {
            $missing.Add($fleetNode)
        }
    }
    if ($missing.Count -gt 0) {
        Fail "expected remote fleet node(s) not found in mesh output: $($missing -join ', ')"
    }
    Write-Host "fleet node check passed (remote peers: $($expectedRemoteNodes -join ', '); local conductor skipped: $($Plan.Conductor))"
}

function Write-SampleManifest([string]$Path) {
    if ((Test-Path -LiteralPath $Path) -and -not $Force) {
        Fail "manifest already exists: $Path (use -Force to overwrite)"
    }
    $sample = @'
{
  "nodes": ["m1", "m2", "m3", "m4", "m5"],
  "conductor": "m1",
  "main": {
    "repo": "D:\\Projects\\main-project",
    "team": "main",
    "watch": "main",
    "task": "phase2 main smoke run",
    "test": "cargo test --quiet",
    "merge": true,
    "routes": {
      "codex": "m1",
      "claude": "m2",
      "agy": "m3"
    }
  },
  "satellites": [
    {
      "name": "sat-a",
      "repo": "D:\\Projects\\sat-a",
      "node": "m2",
      "team": "sat-a",
      "watch": "sat-a",
      "task": "phase2 satellite A smoke run",
      "test": "cargo test --quiet"
    },
    {
      "name": "sat-b",
      "repo": "D:\\Projects\\sat-b",
      "node": "m3",
      "team": "sat-b",
      "watch": "sat-b",
      "task": "phase2 satellite B smoke run",
      "test": "cargo test --quiet"
    },
    {
      "name": "sat-c",
      "repo": "D:\\Projects\\sat-c",
      "node": "m4",
      "team": "sat-c",
      "watch": "sat-c",
      "task": "phase2 satellite C smoke run",
      "test": "cargo test --quiet"
    },
    {
      "name": "sat-d",
      "repo": "D:\\Projects\\sat-d",
      "node": "m5",
      "team": "sat-d",
      "watch": "sat-d",
      "task": "phase2 satellite D smoke run",
      "test": "cargo test --quiet"
    }
  ]
}
'@
    $dir = Split-Path -Parent $Path
    if ($dir) {
        New-Item -ItemType Directory -Force -Path $dir | Out-Null
    }
    Set-Content -LiteralPath $Path -Value $sample -Encoding utf8NoBOM
    Write-Host "wrote sample manifest: $Path"
}

function Invoke-SelfTest {
    $root = Join-Path ([System.IO.Path]::GetTempPath()) ("ensemble-phase2-fleet-" + [System.Guid]::NewGuid().ToString("N"))
    New-Item -ItemType Directory -Force -Path $root | Out-Null
    $mainRepo = Join-Path $root "main"
    $satRepo = Join-Path $root "sat-a"
    New-Item -ItemType Directory -Force -Path $mainRepo, $satRepo | Out-Null
    $json = @{
        nodes      = @("m1", "m2")
        conductor  = "m1"
        main       = @{
            repo   = $mainRepo
            test   = "echo main"
            routes = @{
                codex  = "m1"
                claude = "m2"
                agy    = "m2"
            }
        }
        satellites = @(
            @{
                name = "sat-a"
                repo = $satRepo
                node = "m2"
                test = "echo sat"
            }
        )
    } | ConvertTo-Json -Depth 6
    $manifestPath = Join-Path $root "fleet.json"
    Set-Content -LiteralPath $manifestPath -Value $json -Encoding utf8NoBOM
    $fleet = Read-FleetManifest $manifestPath
    $plan = New-FleetPlan $fleet $root
    $main = @($plan.Projects | Where-Object { $_.Kind -eq "main" })[0]
    if ($main.Text -notmatch 'node = "http://m1:7878"') {
        Fail "self-test expected main codex route to be normalized"
    }
    if ((Normalize-NodeUrl "m2:9000") -ne "http://m2:9000") {
        Fail "self-test expected host:port to be preserved"
    }
    if ($main.Text -notmatch 'min_approvals = 2') {
        Fail "self-test expected main quorum to stay 2"
    }
    if (-not (Test-HostPresent "m2" @("m2.tail.ts.net"))) {
        Fail "self-test expected short host to match MagicDNS host"
    }
    if (Test-HostPresent "m1" @("m10.tail.ts.net")) {
        Fail "self-test expected m1 not to match m10"
    }
    $script:Node = "m2"
    $nodePlan = New-FleetPlan $fleet $root
    $sat = @($nodePlan.Projects | Where-Object { $_.Name -eq "sat-a" })[0]
    if (-not $sat.Selected) {
        Fail "self-test expected m2 satellite to be selected"
    }
    if ($sat.Text -match 'backup = "agy"') {
        Fail "self-test expected satellite generated crew to stay codex+claude only"
    }
    if ($sat.Text -notmatch 'node = "http://m2:7878"') {
        Fail "self-test expected satellite node to be normalized"
    }
    Write-Host "phase2-fleet self-test passed"
}

if ($SelfTest) {
    Invoke-SelfTest
    exit 0
}

$manifestPath = Resolve-ManifestPath $Manifest
if ($InitSample) {
    Write-SampleManifest $manifestPath
    exit 0
}

$manifestDir = Split-Path -Parent $manifestPath
$fleet = Read-FleetManifest $manifestPath
$plan = New-FleetPlan $fleet $manifestDir

if ($Materialize) {
    Materialize-Plan $plan
}
if ($CheckNodes) {
    Check-FleetNodes $plan
}
if ($PlanOnly -or (-not $Materialize -and -not $CheckNodes)) {
    Write-Plan $plan
}
